version: "3.5"

services:
  hugo:
    image: klakegg/hugo:alpine
    container_name: ssg
    working_dir: /var/www/blog/src
    command: server -D
    ports:
      - 1313:1313
    volumes:
      - type: bind
        source: ./src
        target: /var/www/blog/src

  nginx:
    image: nginx:1.21.3
    container_name: web
    ports:
      - 8888:80
      - 8889:443
    volumes:
      - type: bind
        source: ./src
        target: /var/www/blog/src
      - type: bind
        source: ./nginx/server.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx/server.ssl.conf
        target: /etc/nginx/conf.d/server.ssl.conf
      - type: bind
        source: ./nginx/certs
        target: /etc/nginx/certs
      - type: bind
        source: ./logs
        target: /var/log/nginx
